### ISSUE TITLE
Can't find the "Explainer" for hiclass

### ISSUE THREAD

**Issue by RamSnoussi** [scikit-learn-contrib/hiclass#123]
Hi, 
I can't find the Explainer for hiclass. what's the problem?

```
from hiclass import Explainer
```
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[5], line 1
----> 1 from hiclass import Explainer

ImportError: cannot import name 'Explainer' from 'hiclass' (/home/anaconda3/lib/python3.9/site-packages/hiclass/__init__.py)
```
hiclass: 3.0.3
python: 3.9
conda: 24.4.0

**Comment by mirand863** [comment]
Hi @RamSnoussi,

I believe you already fixed the problem. But for posterity, the explainer class only started to get introduced in the library in version 4.8.0 for the local classifier per parent node, while the latest version 4.10.0 should have this implemented for all 3 local hierarchical classifiers. It is still experimental and will probably have updates in the near future. @ashishpatel16 @dniprocat
