### ISSUE TITLE
Handle Precision and Recall equal to zero when building F1 score

### ISSUE THREAD

**Issue by johanmazelanssi** [scikit-learn-contrib/hiclass#133]
**Problem description**
If there is no predicted instances for a given class, both Precision and Recall for this class are 0.
The problem happens when using average="macro".
I think that the F1 score building fails because this [line](https://github.com/scikit-learn-contrib/hiclass/blob/5ee9b59ec792725c81e3f58c7fd4593833649549/hiclass/metrics.py#L238) does not check that there is no division by zero.

Here is a minimal example:
```
from sklearn.metrics import f1_score
from hiclass import metrics

y_true = [0, 1]
y_pred = [1, 1]

f1_score(y_true, y_pred, average='macro')
metrics.f1(y_true, y_pred, average='macro')
```

**Solution**
The f1 function should return 0 if Precision+Recall=0.
Additionally, the f1 function may also include a "zero_division" parameter as [scikit learn's f1_score function](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html).

**Comment by mirand863** [comment]
Hi @johanmazelanssi,

Thank you for catching this error. I added the zero_division parameter in PR #136, which also fixes this error. I will merge it shortly if all tests pass.
