### ISSUE TITLE
Support for python 3.12

### ISSUE THREAD

**Issue by PRFina** [scikit-learn-contrib/hiclass#134]
Hello! Is there any specific reason for [not supporting Python 3.12](https://github.com/scikit-learn-contrib/hiclass/blob/main/setup.py#L26)? I've checked all the base dependencies already support it
Any plan to add support?

**Comment by chef88314** [comment]
Maybe you can try to re-install the Anaconda because it will install Python 3.7 or 3.8, meanwhile, make sure you have installed it in the right place. If it doesn't working, try to uninstall the Python 3.12 manually and install the correct version.

**Comment by mirand863** [comment]
Hi @PRFina,

Thank you for checking the dependencies. I just created a pull request to add support for python 3.12 and will merge it shortly
