### ISSUE TITLE
Error with Empty Level example

### ISSUE THREAD

**Issue by sciencecw** [scikit-learn-contrib/hiclass#84]
I run into the following error with [the empty level example script](https://hiclass.readthedocs.io/en/latest/auto_examples/plot_empty_levels.html)

**Desktop :**
 - OS: MacOS
 - Python 3.10.9 

![Screenshot 2023-02-22 at 3 58 46 PM](https://user-images.githubusercontent.com/10662708/220757700-967b4fe1-f3f7-464a-bc2e-211f6c863c8f.png)

**Comment by mirand863** [comment]
Hi @sciencecw,

Do you have a reason to be using python 3.10? The only versions supported at the moment are python >= 3.7 <= 3.9

**Comment by sciencecw** [comment]
Hi @mirand863 ,

That answers the question. I will use a supported version. 

Thanks!

**Comment by mirand863** [comment]
@sciencecw,

Great! Please, do let me know if you find any issues when using the supported versions.

Kind regards,
Fabio
