### ISSUE TITLE
Error when using sklearn KNN

### ISSUE THREAD

**Issue by maria407** [scikit-learn-contrib/hiclass#88]
I was testing your tool on your example data with KNN classifier as base. I had no problem with other sklearn classifiers as Random Forest, Logistic Regression
It returns error:
TypeError: fit() takes 3 positional arguments but 4 were given

**Comment by mirand863** [comment]
Hi @maria407,

Thank you for reporting this bug! I will take a look into this issue on Monday and give you an update then.

Kind regards,
Fabio

**Comment by mirand863** [comment]
Hi @maria407,

Apologies for the delay. I just pushed a fix for this bug and I am releasing version 4.3.4 that contains the fix. You can install it with `pip install hiclass==4.3.4` and the conda installation will be uploaded by the conda bot shortly (can take some hours). I am closing the issue, but if you run into further problems, please reopen it or open a new one if it is unrelated.

Best regards,
Fabio
