### ISSUE TITLE
Handling of common children in hierarchy tree

### ISSUE THREAD

**Issue by astronights** [scikit-learn-contrib/hiclass#95]
Hi,

I have a use case where at some level in the hierarchy there are children that share the same class name.

How does HiClass handle this and is this safe or do these need to be deduplicated before hand?

I am looking for a representation as such

```
     A
   /   \
  B     C
 |      |
 D      D
 |      | 
 E      F

```
And not like this:

```
     A
    / \
   B   C
    \ / 
     D
   /  \
  E    F
```

Can you help provide some insight into if there is support for this type of hierarchical tree?
Thanks!

**Comment by mirand863** [comment]
Hi @astronights,

Thank you for the interest in HiClass!

HiClass recognizes ambiguities and handles them accordingly. That means that in your example it would still treat these as separate nodes since they are coming from different parents. Here is a small example:

```python
import numpy as np
from sklearn.linear_model import LogisticRegression

from hiclass import LocalClassifierPerNode

# Define data
X_train = [[1, 2], [3, 4]]
X_test = [[3, 4], [1, 2]]
Y_train = np.array(
    [
        ["A", "B", "D", "E"],
        ["A", "C", "D", "F"],
    ],
    dtype=object,
)

# Use random forest classifiers for every node
rf = LogisticRegression()
classifier = LocalClassifierPerNode(local_classifier=rf)

# Train local classifier per node
classifier.fit(X_train, Y_train)

# Predict
predictions = classifier.predict(X_test)
print(predictions)
```
Please, let me know if this answers your question.

**Comment by astronights** [comment]
Thank you for the clarification. Good to know that these discrepancies are handled.
